// ─────────────────────────────────────────────
// LogiAI — Demo Data (mutable in-memory store)
// Used when NEXT_PUBLIC_SUPABASE_URL is not set
// ─────────────────────────────────────────────

function uid() {
  return Math.random().toString(36).slice(2) + Date.now().toString(36);
}

function daysFromNow(n) {
  const d = new Date();
  d.setDate(d.getDate() + n);
  return d.toISOString().slice(0, 10);
}

export const DEMO_DATA = {
  warehouses: [
    { id: uid(), warehouse_id:'WH-001', name:'Chicago DC',        facility_type:'Distribution Center', utilization_pct:87, capacity_sqft:50000, dock_doors:24, available_doors:6,  location:'Chicago, IL',     created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
    { id: uid(), warehouse_id:'WH-002', name:'Los Angeles FC',    facility_type:'Fulfillment Center',  utilization_pct:72, capacity_sqft:35000, dock_doors:18, available_doors:9,  location:'Los Angeles, CA',  created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
    { id: uid(), warehouse_id:'WH-003', name:'Dallas XD',         facility_type:'Cross-Dock',          utilization_pct:94, capacity_sqft:20000, dock_doors:32, available_doors:3,  location:'Dallas, TX',       created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
    { id: uid(), warehouse_id:'WH-004', name:'Atlanta DC',        facility_type:'Distribution Center', utilization_pct:61, capacity_sqft:45000, dock_doors:20, available_doors:11, location:'Atlanta, GA',      created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
    { id: uid(), warehouse_id:'WH-005', name:'Seattle XD',        facility_type:'Cross-Dock',          utilization_pct:78, capacity_sqft:15000, dock_doors:16, available_doors:5,  location:'Seattle, WA',      created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  ],

  customers: [
    { id: uid(), customer_number:'CUST-001', company_name:'Apex Industries',       sla_tier:'Platinum', annual_value_usd:2400000, active_orders:48, on_time_rate:98.2, risk_score:8,  credit_limit_usd:5000000, status:'Active',  created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
    { id: uid(), customer_number:'CUST-002', company_name:'NovaTech Corp',         sla_tier:'Platinum', annual_value_usd:1800000, active_orders:32, on_time_rate:97.1, risk_score:11, credit_limit_usd:4000000, status:'Active',  created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
    { id: uid(), customer_number:'CUST-003', company_name:'Pacific Rim Traders',   sla_tier:'Gold',     annual_value_usd:980000,  active_orders:24, on_time_rate:94.3, risk_score:22, credit_limit_usd:2000000, status:'Active',  created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
    { id: uid(), customer_number:'CUST-004', company_name:'Midwest Grain Co',      sla_tier:'Gold',     annual_value_usd:720000,  active_orders:18, on_time_rate:91.7, risk_score:28, credit_limit_usd:1500000, status:'Active',  created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
    { id: uid(), customer_number:'CUST-005', company_name:'Atlas Distribution',    sla_tier:'Gold',     annual_value_usd:550000,  active_orders:22, on_time_rate:89.4, risk_score:35, credit_limit_usd:1200000, status:'Active',  created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
    { id: uid(), customer_number:'CUST-006', company_name:'Zenith Medical',        sla_tier:'Platinum', annual_value_usd:2100000, active_orders:41, on_time_rate:96.8, risk_score:12, credit_limit_usd:4500000, status:'Active',  created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
    { id: uid(), customer_number:'CUST-007', company_name:'Cornerstone Retail',    sla_tier:'Standard', annual_value_usd:320000,  active_orders:9,  on_time_rate:85.2, risk_score:45, credit_limit_usd:600000,  status:'Active',  created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
    { id: uid(), customer_number:'CUST-008', company_name:'BlueStar Logistics',    sla_tier:'Standard', annual_value_usd:280000,  active_orders:7,  on_time_rate:82.1, risk_score:52, credit_limit_usd:500000,  status:'On Hold', created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
    { id: uid(), customer_number:'CUST-009', company_name:'Ironwood Manufacturing', sla_tier:'Gold',    annual_value_usd:660000,  active_orders:19, on_time_rate:90.3, risk_score:31, credit_limit_usd:1400000, status:'Active',  created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
    { id: uid(), customer_number:'CUST-010', company_name:'Cascade Foods',         sla_tier:'Standard', annual_value_usd:190000,  active_orders:5,  on_time_rate:78.9, risk_score:61, credit_limit_usd:400000,  status:'Active',  created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  ],

  vehicles: [
    { id: uid(), vehicle_number:'TRK-0001', vin:'1HTMM12345001', driver_name:'Marcus Johnson',    eld_status:'Connected',   hos_status:'D',   drive_remaining_minutes:440, fuel_percent:78.5, odometer_miles:125000, status:'Moving',  cargo_type:'Electronics',        speed_mph:63, latitude:41.88, longitude:-87.63, created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
    { id: uid(), vehicle_number:'TRK-0002', vin:'1HTMM12345002', driver_name:'Tyler Williams',    eld_status:'Connected',   hos_status:'D',   drive_remaining_minutes:380, fuel_percent:62.1, odometer_miles:204000, status:'Moving',  cargo_type:'Auto Parts',         speed_mph:58, latitude:34.05, longitude:-118.24, created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
    { id: uid(), vehicle_number:'TRK-0003', vin:'1HTMM12345003', driver_name:'Elena Rodriguez',   eld_status:'Connected',   hos_status:'D',   drive_remaining_minutes:510, fuel_percent:91.3, odometer_miles:88000,  status:'Moving',  cargo_type:'Pharma·Cold Chain',  speed_mph:71, latitude:33.45, longitude:-112.07, created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
    { id: uid(), vehicle_number:'TRK-0004', vin:'1HTMM12345004', driver_name:'Jason Chen',        eld_status:'Connected',   hos_status:'ON',  drive_remaining_minutes:0,   fuel_percent:45.2, odometer_miles:312000, status:'Stopped', cargo_type:'Foodstuff',          speed_mph:0,  latitude:32.78, longitude:-96.80,  created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
    { id: uid(), vehicle_number:'TRK-0005', vin:'1HTMM12345005', driver_name:'Patricia Thompson', eld_status:'Malfunction', hos_status:'D',   drive_remaining_minutes:55,  fuel_percent:23.8, odometer_miles:445000, status:'Alert',   cargo_type:'Hazmat',             speed_mph:0,  latitude:29.76, longitude:-95.37,  created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
    { id: uid(), vehicle_number:'TRK-0006', vin:'1HTMM12345006', driver_name:'David Garcia',      eld_status:'Connected',   hos_status:'D',   drive_remaining_minutes:620, fuel_percent:88.0, odometer_miles:67000,  status:'Moving',  cargo_type:'General Freight',    speed_mph:68, latitude:47.61, longitude:-122.33, created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
    { id: uid(), vehicle_number:'TRK-0007', vin:'1HTMM12345007', driver_name:'Rachel Martinez',   eld_status:'Connected',   hos_status:'D',   drive_remaining_minutes:390, fuel_percent:71.4, odometer_miles:178000, status:'Moving',  cargo_type:'Reefer·Produce',     speed_mph:55, latitude:37.77, longitude:-122.42, created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
    { id: uid(), vehicle_number:'TRK-0008', vin:'1HTMM12345008', driver_name:'Kevin Anderson',    eld_status:'Connected',   hos_status:'SB',  drive_remaining_minutes:0,   fuel_percent:55.6, odometer_miles:256000, status:'Stopped', cargo_type:'Electronics',        speed_mph:0,  latitude:39.74, longitude:-104.99, created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
    { id: uid(), vehicle_number:'TRK-0009', vin:'1HTMM12345009', driver_name:'Sandra Taylor',     eld_status:'Connected',   hos_status:'D',   drive_remaining_minutes:470, fuel_percent:67.9, odometer_miles:143000, status:'Moving',  cargo_type:'Auto Parts',         speed_mph:61, latitude:25.76, longitude:-80.19,  created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
    { id: uid(), vehicle_number:'TRK-0010', vin:'1HTMM12345010', driver_name:'James Wilson',      eld_status:'Connected',   hos_status:'D',   drive_remaining_minutes:290, fuel_percent:38.1, odometer_miles:389000, status:'Moving',  cargo_type:'General Freight',    speed_mph:49, latitude:44.98, longitude:-93.27,  created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  ],

  drivers: [
    { id: uid(), driver_number:'DRV-001', full_name:'Marcus Johnson',    cdl_license:'CDL-A-100001', eld_status:'Connected',   hos_status:'D',   drive_remaining_minutes:440, safety_score:97.2, vehicle_number:'TRK-0001', status:'Active',   created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
    { id: uid(), driver_number:'DRV-002', full_name:'Tyler Williams',    cdl_license:'CDL-A-100002', eld_status:'Connected',   hos_status:'D',   drive_remaining_minutes:380, safety_score:93.8, vehicle_number:'TRK-0002', status:'Active',   created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
    { id: uid(), driver_number:'DRV-003', full_name:'Elena Rodriguez',   cdl_license:'CDL-A-100003', eld_status:'Connected',   hos_status:'D',   drive_remaining_minutes:510, safety_score:98.5, vehicle_number:'TRK-0003', status:'Active',   created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
    { id: uid(), driver_number:'DRV-004', full_name:'Jason Chen',        cdl_license:'CDL-A-100004', eld_status:'Connected',   hos_status:'ON',  drive_remaining_minutes:0,   safety_score:88.1, vehicle_number:'TRK-0004', status:'Active',   created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
    { id: uid(), driver_number:'DRV-005', full_name:'Patricia Thompson', cdl_license:'CDL-A-100005', eld_status:'Malfunction', hos_status:'D',   drive_remaining_minutes:55,  safety_score:72.4, vehicle_number:'TRK-0005', status:'Active',   created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
    { id: uid(), driver_number:'DRV-006', full_name:'David Garcia',      cdl_license:'CDL-A-100006', eld_status:'Connected',   hos_status:'D',   drive_remaining_minutes:620, safety_score:99.1, vehicle_number:'TRK-0006', status:'Active',   created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
    { id: uid(), driver_number:'DRV-007', full_name:'Rachel Martinez',   cdl_license:'CDL-A-100007', eld_status:'Connected',   hos_status:'D',   drive_remaining_minutes:390, safety_score:91.3, vehicle_number:'TRK-0007', status:'Active',   created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
    { id: uid(), driver_number:'DRV-008', full_name:'Kevin Anderson',    cdl_license:'CDL-A-100008', eld_status:'Connected',   hos_status:'SB',  drive_remaining_minutes:0,   safety_score:85.6, vehicle_number:'TRK-0008', status:'Off Duty', created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
    { id: uid(), driver_number:'DRV-009', full_name:'Sandra Taylor',     cdl_license:'CDL-A-100009', eld_status:'Connected',   hos_status:'D',   drive_remaining_minutes:470, safety_score:94.7, vehicle_number:'TRK-0009', status:'Active',   created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
    { id: uid(), driver_number:'DRV-010', full_name:'James Wilson',      cdl_license:'CDL-A-100010', eld_status:'Connected',   hos_status:'D',   drive_remaining_minutes:290, safety_score:79.2, vehicle_number:'TRK-0010', status:'Active',   created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  ],

  orders: [
    { id: uid(), order_number:'ORD-8001', customer_name:'Apex Industries',    sla_tier:'Platinum', origin:'CHICAGO',       destination:'DETROIT',      items:12, weight_kg:4200,  status:'In Transit',  eta: daysFromNow(3),  notes:'', created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
    { id: uid(), order_number:'ORD-8002', customer_name:'NovaTech Corp',      sla_tier:'Platinum', origin:'LOS ANGELES',   destination:'MIAMI',         items:8,  weight_kg:1800,  status:'Pending',     eta: daysFromNow(5),  notes:'', created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
    { id: uid(), order_number:'ORD-8003', customer_name:'Pacific Rim Traders',sla_tier:'Gold',     origin:'DALLAS',        destination:'BOSTON',        items:24, weight_kg:6500,  status:'In Transit',  eta: daysFromNow(2),  notes:'', created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
    { id: uid(), order_number:'ORD-8004', customer_name:'Zenith Medical',     sla_tier:'Platinum', origin:'ATLANTA',       destination:'CHICAGO',       items:3,  weight_kg:420,   status:'Delayed',     eta: daysFromNow(1),  notes:'Cold chain issue', created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
    { id: uid(), order_number:'ORD-8005', customer_name:'Midwest Grain Co',   sla_tier:'Gold',     origin:'PHOENIX',       destination:'LAS VEGAS',     items:16, weight_kg:12000, status:'Processing',  eta: daysFromNow(4),  notes:'', created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
    { id: uid(), order_number:'ORD-8006', customer_name:'Atlas Distribution', sla_tier:'Gold',     origin:'SEATTLE',       destination:'PORTLAND',      items:7,  weight_kg:2100,  status:'Delivered',   eta: daysFromNow(0),  notes:'', created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
    { id: uid(), order_number:'ORD-8007', customer_name:'Cascade Foods',      sla_tier:'Standard', origin:'HOUSTON',       destination:'DALLAS',        items:9,  weight_kg:3400,  status:'Pending',     eta: daysFromNow(6),  notes:'', created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
    { id: uid(), order_number:'ORD-8008', customer_name:'Ironwood Manufacturing',sla_tier:'Gold',  origin:'DETROIT',       destination:'MINNEAPOLIS',   items:5,  weight_kg:890,   status:'In Transit',  eta: daysFromNow(3),  notes:'', created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
    { id: uid(), order_number:'ORD-8009', customer_name:'Cornerstone Retail', sla_tier:'Standard', origin:'SAN FRANCISCO', destination:'DENVER',        items:11, weight_kg:2800,  status:'Processing',  eta: daysFromNow(5),  notes:'', created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
    { id: uid(), order_number:'ORD-8010', customer_name:'BlueStar Logistics', sla_tier:'Standard', origin:'NEW YORK',      destination:'ATLANTA',       items:6,  weight_kg:1650,  status:'Delayed',     eta: daysFromNow(2),  notes:'', created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  ],

  shipments: [
    { id: uid(), bol_number:'BOL-2024001', scac:'USX',  incoterms:'FOB', origin:'USCHICAGO',     destination:'USDETROIT',      vehicle_id:'TRK-0001', eta: daysFromNow(3),  temp_celsius:null, temp_alert:false, status:'In Transit',   created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
    { id: uid(), bol_number:'BOL-2024002', scac:'FDX',  incoterms:'DDP', origin:'USLOSANGELES',  destination:'USMIAMI',        vehicle_id:'TRK-0002', eta: daysFromNow(5),  temp_celsius:null, temp_alert:false, status:'Booked',       created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
    { id: uid(), bol_number:'BOL-2024003', scac:'UPSF', incoterms:'DAP', origin:'USDALLAS',      destination:'USBOSTON',       vehicle_id:'TRK-0003', eta: daysFromNow(2),  temp_celsius:5.8,  temp_alert:false, status:'In Transit',   created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
    { id: uid(), bol_number:'BOL-2024004', scac:'CNWY', incoterms:'EXW', origin:'USATLANTA',     destination:'USCHICAGO',      vehicle_id:'TRK-0005', eta: daysFromNow(1),  temp_celsius:null, temp_alert:false, status:'Customs Hold', created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
    { id: uid(), bol_number:'BOL-2024005', scac:'ABFS', incoterms:'FCA', origin:'USPHOENIX',     destination:'USLASVEGAS',     vehicle_id:'TRK-0006', eta: daysFromNow(4),  temp_celsius:null, temp_alert:false, status:'Gate In',      created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
    { id: uid(), bol_number:'BOL-2024006', scac:'RDWY', incoterms:'CPT', origin:'USSEATTLE',     destination:'USPORTLAND',     vehicle_id:'TRK-0007', eta: daysFromNow(0),  temp_celsius:null, temp_alert:false, status:'POD Signed',   created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
    { id: uid(), bol_number:'BOL-2024007', scac:'HNRY', incoterms:'FOB', origin:'USHOUSTON',     destination:'USDALLAS',       vehicle_id:'TRK-0008', eta: daysFromNow(6),  temp_celsius:null, temp_alert:false, status:'Booked',       created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
    { id: uid(), bol_number:'BOL-2024008', scac:'DAFG', incoterms:'DAP', origin:'USDETROIT',     destination:'USMINNEAPOLIS',  vehicle_id:'TRK-0009', eta: daysFromNow(3),  temp_celsius:2.1,  temp_alert:false, status:'In Transit',   created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
    { id: uid(), bol_number:'BOL-2024009', scac:'EXLA', incoterms:'DDP', origin:'USSANFRAN',     destination:'USDENVER',       vehicle_id:'TRK-0010', eta: daysFromNow(5),  temp_celsius:null, temp_alert:false, status:'Gate Out',     created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
    { id: uid(), bol_number:'BOL-2024010', scac:'USX',  incoterms:'FOB', origin:'USNYC',         destination:'USATLANTA',      vehicle_id:'TRK-0001', eta: daysFromNow(2),  temp_celsius:-2.3, temp_alert:true,  status:'In Transit',   created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  ],

  alerts: [
    { id: uid(), type:'critical', title:'TEMP ALERT: BOL-2024010',   message:'Reefer unit exceeding set-point by 3.8°C — pharmaceutical SLA breach imminent', entity_type:'shipment', entity_id:'BOL-2024010', resolved:false, created_at: new Date().toISOString() },
    { id: uid(), type:'warning',  title:'HOS Warning: DRV-005',      message:'Patricia Thompson has only 55 min drive time remaining', entity_type:'driver', entity_id:'DRV-005', resolved:false, created_at: new Date().toISOString() },
    { id: uid(), type:'critical', title:'ELD Malfunction: TRK-0005', message:'ELD device reporting malfunction — manual log required', entity_type:'vehicle', entity_id:'TRK-0005', resolved:false, created_at: new Date().toISOString() },
    { id: uid(), type:'info',     title:'WH-003 at 94% Capacity',    message:'Dallas XD at overflow threshold — authorize alternate cross-dock', entity_type:'warehouse', entity_id:'WH-003', resolved:false, created_at: new Date().toISOString() },
    { id: uid(), type:'success',  title:'BOL-2024006 Delivered',     message:'POD signed at USPORTLAND facility', entity_type:'shipment', entity_id:'BOL-2024006', resolved:true, created_at: new Date().toISOString() },
  ],
};
